language: python
python:
  - "3.6"
services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests -v --with-coverage --cover-tests --cover-package=tests
after_success:
  - coveralls
