"""empty message

Revision ID: 116f1f93a613
Revises: 1042259f3199
Create Date: 2018-12-28 03:39:01.823938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116f1f93a613'
down_revision = '1042259f3199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobposts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('resumes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jobposts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
